package com.fdzcxy.zerotime.Utiles;

/**
 * 英语单词数据
 * 
 * @author Administrator
 * 
 */
public class EnglishWord {

	/**
	 * 英文拼写
	 */
	public static String[] WORD_SPELLING = { "the", "be", "of", "and", "a",
			"to", "in", "he", "have", "it", "that", "for", "they", "I", "with",
			"as", "not", "on", "she", "at", "by", "this", "we", "you", "do",
			"but", "from", "or", "which", "one", "would", "all", "will",
			"there", "say", "who", "make", "when", "can", "more", "if", "no",
			"man", "out", "other", "so", "what", "time", "up", "go", "about",
			"than", "into", "could", "state", "only", "new", "year", "some",
			"take", "come", "these", "know", "see", "use", "get", "like",
			"then", "first", "any", "work", "now", "may", "such", "give",
			"over", "think", "most", "even", "find", "day", "also", "after",
			"way", "many", "must", "look", "before", "great", "back",
			"through", "long", "where", "much", "should", "well", "people",
			"down", "own", "just", "because", "good", "each", "those", "feel",
			"seem", "how", "high", "too", "place", "little", "world", "very",
			"still", "nation", "hand", "old", "life", "tell", "write",
			"become", "here", "show", "house", "both", "between", "need",
			"mean", "call", "develop", "under", "last", "right", "move",
			"thing", "general", "school", "never", "same", "another", "begin",
			"while", "number", "part", "turn", "real", "leave", "might",
			"want", "point", "form", "off", "child", "few", "small", "since",
			"against", "ask", "late", "home", "interest", "large", "person",
			"end", "open", "public", "follow", "during", "present", "without",
			"again", "hold", "govern", "around", "possible", "head",
			"consider", "word", "program", "problem" };

	/**
	 * 中文意思
	 */
	public static String[] WORD_MEANING = { "art.这，那 ad.[用于比较级；最高级前]",
			"aux. v.(am,is,are之原型) vi.是;在", "prep.…的；由…制成的；关于；由于",
			"conj.和；那么;然后;而且", "art.一(个)；任何一(个)；每一(个)",
			"prep.向；对；趋于；直到…为止；比；到", "prep.在…里；以；穿着；由于 ad.进；到达",
			"pron.他；(不论性别的)一个人", "aux. v.已经 vt.有；进行；经受；吃；取得", "pron.它；这；那",
			"a./ pron.那，那个； ad.那样，那么", "prep.为；对，供，适合于；向 conj.因为故",
			"pron.他(或她、它)们", "pron.我", "prep.和，跟，同；具有；用；关于；随着",
			"ad.同样地 prep.当作 conj.随着;因为", "ad.不，没，不是",
			"prep.在…上；向；处于；在 ad.上；向前", "pron.她", "prep.在;向;以;处于;因为;从事",
			"prep.被；凭借；经由；由于 ad.在近旁；经过", "a.这，这个；今，本 pron.这，这个", "pron.我们",
			"pron.你，你们", "aux. v.[代替动词] v.做，干，行动",
			"conj.但是；而(是) prep.除…以外 ad.只", "prep.出自；离；去除；从；因为；由；与",
			"conj.或，或者；或者说；否则，要不然", "pron./ a.哪一个(些)；[关系代词]那个(些)",
			"num.一 pron.一个(人) a.一个的；一体的", "aux. v.[will的过去式]；总会；也许；请",
			"a.全部的；尽量的 ad.很 pron.全部", "aux. v.将；愿意 n.意志；遗嘱 vt.用意志驱使",
			"pron.[与be连用，“有”] ad.在那里", "v.说；表明 ad.比如说，大约 n.发言权",
			"pron.谁，什么人；[关系代词]…的人", "vt.做，制造；产生；成为 n.品牌，类型",
			"ad./ pron.什么时候；在…时 conj.当…时", "aux. v.能；可以 n.罐(头) vt.把…装罐保存",
			"ad.更(多) a.更多(大)的 n.更多的人(或物)", "conj.如果，假如；是否；即使；无论何时",
			"ad.不，不是，没有 a.没有的；不许的", "n.(成年)男人；人，人类 vt.给…配备人员",
			"ad.出，向外；在外；出现；完；过时", "a.别的；其余的 pron.另一个人(或物)",
			"ad.那么，非常；如此 conj.所以；以便", "pron.什么；[关系代词] a.多么；什么",
			"n.时间；次；倍[ pl.]时期 vt.为…安排时间", "ad./ a.向上(的) prep.沿…往上；在…上面",
			"vi.去；变得；进行；放；通往；消失 n.尝试", "[əˈbaut] prep.关于；在…周围 ad.大约；在附近",
			"conj.比", "prep.进，入，到…里；成为；很喜欢", "v. aux.can的过去式；[虚拟语气等]可以(能)",
			"n.状态；国家，政府；州 vt.陈述，说明", "ad.只；反而 a.唯一的；最好的 conj.可是",
			"a.新的，新出现的，新生产的；生疏的", "n.年，年份", "a.一些，有些；某个 pron.一些 ad.大约",
			"vt.带(去)；做；花费；拿；服用；乘；拍", "vi.来(自)；经过；至；实现；开始；发生",
			"pron.[this的复数]这些", "v.知道；认识；会；认出，分辨；懂得", "v.知道；认识；会；认出，分辨；懂得",
			"vt.用；耗费，利用 n.使用，应用；用途", "vt.获得；收到；理解 vi.变得；逐渐；到达",
			"v.喜欢 n.[ pl.]相似(物) prep.像 a.相像的", "ad.当时；那么，因而；然后，于是",
			"num.第一 a.第一的 ad.首先；第一次；宁可", "pron.无论哪个; a.任何的 ad.丝毫",
			"v.工作；有效 n.工作；职业[ pl.]著作", "ad.(到)现在，如今；这时候；马上", "n.五月",
			"a.这样的 ad.那么 pron.这样的人(物)", "vt.给予；提供 vi.塌下，折断，弯曲；让步",
			"prep.在…的上；关于 ad.颠倒地 a.结束的", "vt.认为；想；打算 vi./ n.想，思考",
			"ad.甚至 a.平的；平稳的；双数的 v.(使)平坦", "ad.甚至 a.平的；平稳的；双数的 v.(使)平坦",
			"vt.发现；感到；判决 n.(有价值的)发现物", "n.天，一昼夜；白昼，白天；时期，时代",
			"ad.而且(也)，此外(还)；同样地", "prep./ conj.在…之后 a.以后的 ad.后",
			"n.方法；路；方面[ pl.]习俗 ad.非常", "a.许多的，多的 pron.许多人，许多",
			"aux. v.必须，应该；一定 n.必须做的事", "v.看；显得；朝着；打量 n.看；脸色",
			"prep.在…前 conj.在…以前 ad.以前", "a.大的；伟大的；好极的；擅长的",
			"ad.回原处 n.背;后面 a.后面的 v.后退", "prep.穿过；从头到尾；凭借 ad./ a.自始至终",
			"ad.长(期)的(地) n.长时间 vi.渴望", "ad./ conj.在哪里；在…的地方 pron.哪里",
			"ad.十分； a./  n.多(的)，大量(的)", "aux. v.[shall的过去式]；应当；可能",
			"ad.好地；完全地 int.那末 a.健康的 n.井", "n.人(们)；[the～]人民；民族 vt.居住于",
			"a./ ad.向下(的)，在下面 prep.沿着…而下", "a.自己的 vt.有，拥有",
			"ad.正好；只是；刚才 a.正义的；", "conj.因为", "a.好的；擅长的； n.善，好处[ pl.]商品",
			"pron.各(每)个 a.各，各自的，每 ad.对每个", "pron.[that的复数]那些",
			"vi.觉得；给人以…感觉 vt.摸；认为 n.感觉", "vi.好像，似乎", "ad.怎么，怎样；多么，多少",
			"a.高(级；尚；兴)的 ad.高 n.高峰(潮，水平)", "ad.也，还；太，过于；很，非常",
			"n.地方；职位；名次 vt.放置；任命", "a.小的；短的；不多的 n.极少 ad.毫不",
			"n.(全)世界，地球；世间(人)；界，领域", "ad.很；完全地 a.正是的，真实的；完全的",
			"ad.还；然而 a.静止的 n.剧照 v.(使)平静", "n.国家，民族", "n.手；指针；人手；帮助；手艺 vt.交，递",
			"a.老的；过时的；以前的；老练的", "n.生命；一生；生活，人生；生物；活力", "v.讲(述)，告诉；吩咐；认出；显示；生效",
			"v.写，写字；写作，作曲；写信(给)", "vi.变成，开始变得 vt.适合，同…相称",
			"ad.在(向，到)这里 int.[用于引起注意]", "v./ n.表明；出示；演出，放映；展览(会)",
			"n.房屋；公司；(H-)议院 vt.给…房子住", "a.两个…(都) pron.两者(都)，双方(都)",
			"prep.在…之间；为…所分享", "vt.需要；缺少 aux.v.必须 n.需要；贫困",
			"vt.意思是；意欲 vi.特意 a.吝啬的；平均的", "v./ n.把…叫做;打电话给;叫;访问;电话",
			"vt.发展；制订；产生 vi.生长；发展", "prep./ ad.在…下面；少于；在…情况下",
			"a.刚过去的；最后的 ad.最后 vi.持续", "a./ ad.对(的)；右(的) int.好 n.权利；右",
			"v.搬；动摇；感动 n.动作；移动，搬家", "n.事；物[常 pl.]局面；所有物，用品",
			"a.一般的；总的，普遍的；笼统的 n.将军", "n.学校，学院；上学，学业；学派", "ad.从不，永不；决不，千万不",
			"a.相同的 pron.[the-]同样的人(物)", "pron.再(另)一个 a.再一个的;别的", "v.开始",
			"conj.当…的时；而；虽然 n.一会儿 vt.消磨", "n.数字；号码[常略作N o.]号 vt.编号",
			"n.部分；零件；作用 v.(使)分开 ad.部分地", "v.转动；扭转；(使)变成 n.转向；轮流",
			"a.真的，真正的；真实的，现实的", "v.出发；离开；留下 n.准假；许可；告辞",
			"aux. v.[may的过去式]；可能 n.力量；权势", "v.想要；缺乏 n.不足［ pl.］需要的东西",
			"n.要点，观点；点；时刻 v.指，指明", "n.形式；外形；表格 v.形(构)成，产生",
			"ad.…掉(下)；离开；停止；休息 a.休息的", "n.小孩，儿童；子女，孩子",
			"a.／ n.[表示否定]很少(的)，几乎没有(的)", "a.小的；少的；不重要的",
			"conj./ prep.从…以后；因为 ad.后来", "prep.逆,反(对),违反；对...不利",
			"vt.询问；请求；邀请 vi.(for)请求", "a.晚的；晚期的；最近的 ad.迟，晚",
			"n.家(乡)；原产地 a.家庭(乡)的 ad.回家", "n.兴趣；利息(率)[ pl.]利益 vt.使感兴趣",
			"a.大的；(数量)多的，众多的", "n.人", "n.末尾；尽头；终止；结果 v.结束，终止",
			"a.开的，开放的，公开的 v.开；开始；开放", "a.公众的；公共的；公开的 n.公众，民众",
			"vt.接着；遵照；听懂；注视 vi.(紧)接；懂", "prep.在…期间",
			"a.出席的；现在的 n.现在；礼物 vt.赠(送)", "prep.无，没有 ad.在外面",
			"ad.再(又)一次；到原处；而且", "v.拿；保持；掌握；主持 n.握住；掌握；船舱", "vt.统治，治理，管理；支配，影响",
			"ad.在周围；到处;大约 prep.遍及", "a.可能的，做得到的；可接受的，合理的",
			"n.头(脑)；顶部；领导 vt.领导 vi.朝…行进", "v.考虑，细想；认为，把…看作；考虑到",
			"n.(单)词[ pl.]言语，话；传说；诺言", "n.计(规)划；节目(单)；程序 vt.编程",
			"n.问题，疑难问题；思考题，讨论题" };

	/**
	 * 音标
	 */
	public static String[] WORD_PHONETIC_ALPHABET = { "[ðə, ði:]", "[bi:,bi]",
			"[əv, ə, ɔv]", "[ənd, ænd]", "[ei, ə, æn, ən]", "[tu:, tu, tə]",
			"[in]", "[hi:, hi]", "[hæv,həv]", "[it]", "[ðæt]", "[fə, fɔ:]",
			"[ðei]", "[ai]", "[wið, wiθ]", "[æz, əz]", "[nɔt]", "[ɔn]",
			"[ʃi:, ʃi]", "[æt, ət]", "[bai]", "[ðis]", "[wi:, wi]",
			"[ju, ju:]", "[du, du:]", "[bʌt,bət]", "[frəm,frɔm]", "[ɔ:, ə]",
			"[witʃ]", "[wʌn]", "[wud]", "[ɔ:l]", "[wil]", "[ðɛə]", "[sei]",
			"[hu:]", "[meik]", "[wen]", "[kæn,kən]", "[mɔ:r]", "[if]", "[nəu]",
			"[mæn]", "[aut]", "[ˈʌðə]", "[səu]", "[wɔt, wɑ:t]", "[taim]",
			"[ʌp]", "[gəu]", "[əˈbaut]", "[ðæn, ðən]", "[ˈintu, ˈintə]",
			"[kud]", "[steit]", "[ˈəunli]", "[nju:]", "[jiə, jə:]",
			"[sʌm,səm]", "[teik]", "[kʌm]", "[ði:z]", "[nəu]", "[nəu]",
			"[ju:z, ju:s]", "[get]", "[laik]", "[ðen]", "[fə:st]", "[ˈeni]",
			"[wə:k]", "[nau]", "[mei]", "[sʌtʃ]", "[giv]", "[ˈəuvə]", "[θiŋk]",
			"[məust]", "[ˈi:vən]", "[faind]", "[dei]", "[ˈɔ:lsəu]", "[ˈɑ:ftə]",
			"[wei]", "[ˈmeni]", "[mʌst]", "[luk]", "[biˈfɔ:]", "[greit]",
			"[bæk]", "[θru:]", "[lɔŋ]", "[wɛə]", "[mʌtʃ]", "[ʃud, ʃəd]",
			"[wel]", "[ˈpi:pl]", "[daun]", "[əun]", "[dʒʌst]", "[biˈkɔz]",
			"[gud]", "[ˈi:tʃ]", "[ðəuz]", "[fi:l]", "[si:m]", "[hau]", "[hai]",
			"[tu:]", "[pleis]", "[ˈlitl]", "[wə:ld]", "[ˈveri]", "[stil]",
			"[ˈneiʃən]", "[hænd]", "[əuld]", "[laif]", "[tel]", "[rait]",
			"[biˈkʌm]", "[hiə]", "[ʃəu]", "[haus]", "[bəuθ]", "[biˈtwi:n]",
			"[ni:d]", "[mi:n]", "[kɔ:l]", "[diˈveləp]", "[ˈʌndə]", "[lɑ:st]",
			"[rait]", "[mu:v]", "[θiŋ]", "[ˈdʒenərəl]", "[sku:l]", "[ˈnevə]",
			"[seim]", "[əˈnʌðə]", "[biˈgin]", "[wail]", "[ˈnʌmbə]", "[pɑ:t]",
			"[tə:n]", "[riəl]", "[li:v]", "[mait]", "[wɔnt, wɑ:nt]", "[pɔint]",
			"[fɔ:m]", "[ɔ(:)f]", "[tʃaild]", "[fju:]", "[smɔ:l]", "[sins]",
			"[əˈgenst]", "[ɑ:sk]", "[leit]", "[həum]", "[ˈintrist]", "[lɑ:dʒ]",
			"[ˈpə:sn]", "[end]", "[ˈəupən]", "[ˈpʌblik]", "[ˈfɔləu]",
			"[ˈdjuəriŋ]", "[priˈzent, ˈprezənt]", "[wiˈðaut]", "[əˈgein]",
			"[həuld]", "[ˈgʌvən]", "[əˈraund]", "[ˈpɔsəb(ə)l]", "[hed]",
			"[kənˈsidə]", "[wə:d", "[ˈprəugræm]", "[ˈprɔbləm]" };
}
